### ISSUE TITLE
I get [object Object] instead of the error message on error

### ISSUE THREAD

**Issue by djibarian** [webpack-contrib/stylelint-webpack-plugin#226]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version: 5.24.4
- stylelint-webpack-plugin Version: 2.1.0

### Expected Behavior

A description of the error should be outputted.

### Actual Behavior

Instead “[object Object]” is displayed, no matter the option used in “formatter”.

### How Do We Reproduce?

Only upgraded to webpack 5.

**Comment by djibarian** [comment]
Strangelly, setting “failOnError” or “failOnWarning” the message shows up, but the build in watch mode freezes.

**Comment by KarimTayel** [comment]
> Strangely, setting “failOnError” or “failOnWarning” the message shows up, but the build in watch mode freezes.

The same thing happens to me when using the [webpack-dev-server](https://github.com/webpack/webpack-dev-server) during development. Setting `failOnError: true` outputs an error message in the console, but instead of recompiling the code, the [webpack-dev-server](https://github.com/webpack/webpack-dev-server) hangs completely and I have to restart it.

I faced a similar [issue](https://github.com/webpack-contrib/eslint-webpack-plugin/issues/59#issuecomment-768681963) when using the [eslint-webpack-plugin](https://github.com/webpack-contrib/eslint-webpack-plugin), but I'm not sure if they are related though.

**Comment by ricardogobbosouza** [comment]
Hi @djibarian , @KarimTayel 
Fixed in #230

**Comment by ricardogobbosouza** [comment]
Fixed in v2.2.0
