### ISSUE TITLE
Performance issues when have multiple entries

### ISSUE THREAD

**Issue by minhtranite** [webpack-contrib/stylelint-webpack-plugin#52]
Currently I have a project with about 15 webpack entries. Each entry have own stylesheet file. And here is webpack build time:

- With stylelint-webpack-plugin:
```
webpack building...
webpack built 832650538a0ff1527328 in 21824ms

webpack building...
webpack built 832650538a0ff1527328 in 13755ms
```

- Without stylelint-webpack-plugin
```
webpack built 832650538a0ff1527328 in 8009ms
webpack building...
webpack built 832650538a0ff1527328 in 194ms
webpack building...
webpack built 832650538a0ff1527328 in 204ms
```

**Comment by mciastek** [comment]
I have encountered same issue. Without stylelint-webpack-plugin build takes approx. 300ms. With stylelint-webpack-plugin it takes 10x slower, approx. 3s. What cause that performance issue?

**Comment by renatorib** [comment]
Same issue here.

Without plugin: *500ms*
With plugin: *4200ms*

**Comment by JaKXz** [comment]
Thanks for reporting this! Would anyone like to take a crack at a PR / investigating? This may also be an upstream issue with `stylelint` itself.

**Comment by sergesemashko** [comment]
It seems like the performance issue here is with stylelint itself. I ran just stylelint task alone and had the approximately the same linting time. 
As a workaround:
1. `lintDirtyFilesOnly: true` flag can be used, which lints just touched files. The PR with flag was merged into master, but not released yet.
2. Skip linting of good files and cache failed files, which I suggested in [another issue](https://github.com/JaKXz/stylelint-webpack-plugin/issues/54). 

Of course, fundamentally, this issue should be solved on stylelint level, because it has the biggest impact. 
There are some thoughts about that in [the comment](https://github.com/stylelint/stylelint/issues/2259#issuecomment-272902353).

**Comment by beckend** [comment]
How about forking the stylelint process instead?

**Comment by JaKXz** [comment]
@beckend would you be willing to make a PR that demonstrates what you're suggesting? I'd be interested in something like that if we could write simple integration tests for it :)

**Comment by shellscape** [comment]
Closing as stale due to age and inactivity. If there is still interest in this issue, please do submit a pull request.
